- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: update iptables
  make:
    chdir: /var/lib/{{ item }}
  with_items:
  - iptables
  - ip6tables
- name: update iptables
  service:
    name: "{{ item }}-restore"
    state: restarted
  with_items:
  - iptables
  - ip6tables
