- hosts: all
  strategy: '{{ strategy | default("linear") }}'

  roles:
  - common/firstboot
  - common/profile
  - { role: common/grub, when: ansible_architecture == "x86_64" }
  - common/systemd
  - { role: common/iptables, when: ansible_architecture == "x86_64" }

  vars_files:
  - config/config.yml
  - config/vault.yml

