---
- hosts: localhost
  become: no
  tasks:

    - include: create.yml
      with_items: "{{ range(replicas) | list }}"
      loop_control:
        loop_var: "replica"

  vars_files:
  - config.yml
  - "{{ cloud_provider }}.yml"

- hosts: all
  tasks:
  # Reduce aggressiveness of syncing
  - stat:
      path: /.ansible-sync
    register: syncmark

  - portage: sync=yes
    when: syncmark.stat.exists is defined and not syncmark.stat.exists

  - file:
      path: /.ansible-sync
      state: touch
    when: syncmark.stat.exists is defined and not syncmark.stat.exists

  # detect if systemd is installed
  - shell: qlist -I sys-apps/systemd
    failed_when: False
    register: systemd

  - portage: package={{ item }} state=absent
    when: '"" == systemd.stdout'
    with_items:
    - sys-fs/udev
    - virtual/udev

  - portage: package=dev-vcs/git state=present

  - git:
      repo: https://github.com/0xdc/overlay
      dest: /usr/local/0xdc-overlay

  - file:
      path: /etc/portage/repos.conf
      state: directory

  - copy:
      src: /usr/local/0xdc-overlay/metadata/repos.conf
      dest: /etc/portage/repos.conf/0xdc.conf
      remote_src: True

  - shell: eselect profile set 0xdc:amd64

  - portage: package=sys-apps/systemd
