#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  become: no
  tasks:

    - include: tasks/create.yml
      with_items: "{{ range(replicas) | list }}"
      loop_control:
        loop_var: "replica"

    - pause: seconds=30

  vars_files:
  - config/config.yml
  - config/{{ cloud_provider }}.yml

- hosts: all
  tasks:
  # Reduce aggressiveness of syncing
  - stat:
      path: /.ansible-sync
    register: syncmark

  - portage: sync=yes
    when: syncmark.stat.exists is defined and not syncmark.stat.exists

  - file:
      path: /.ansible-sync
      state: touch

  # I don't have a good non-destructive test for this perl upgrade
  # but this shell command detects and fixes it most of the time
  - shell: '(qlist -IC "virtual/perl-*"; qlist -IC "dev-perl/*") | xargs emerge -1 dev-lang/perl'
  # just run it once, if we sync the tree
    when: syncmark.stat.exists is defined and not syncmark.stat.exists
  # git, the next package, depends on perl rather heavily

  - portage: package=dev-vcs/git state=present

  - git:
      repo: https://github.com/0xdc/overlay
      dest: /usr/local/0xdc-overlay

  - file:
      path: /etc/portage/repos.conf
      state: directory

  - copy:
      src: /usr/local/0xdc-overlay/metadata/repos.conf
      dest: /etc/portage/repos.conf/0xdc.conf
      remote_src: True

  - shell: eselect profile set 0xdc:amd64

  # detect if systemd is installed
  - shell: qlist -I sys-apps/systemd
    failed_when: False
    register: systemd

  - portage: state=absent
    when: '"" == systemd.stdout'
    with_items:
    - sys-fs/udev
    - sys-fs/eudev
    - virtual/udev
    - virtual/dev-manager
    loop_control:
      loop_var: package

  - portage: package=sys-apps/systemd
    # Because we removed udev above, pciutils needs to be built
    # without udev support
    environment:
      USE: -udev
