#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  become: no
  tasks:

    - name: spin up
      include: tasks/replicas.yml
      with_dict: "{{ layout }}"
      loop_control:
        loop_var: "role"

  vars_files:
  - config/config.yml
  - config/layout.yml
  - config/vault.yml
  - config/{{ cloud_provider }}.yml

- hosts: all
  gather_facts: no
  tasks:
  - name: wait for server boot
    include: tasks/wait.yml
  vars_files:
  - config/config.yml
  - config/vault.yml

- hosts: all
  strategy: '{{ strategy | default("linear") }}'

  roles:
  - common/firstboot
  - common/profile
  - common/grub
  - common/systemd

  vars_files:
  - config/config.yml
  - config/vault.yml
