---
- hosts: localhost
  tasks:

  - os_server:
      cloud: "{{ cloud_provider }}"
      region_name: "{{ cloud_region }}"

      name: "{{ server_name }}"
      meta: "role={{ server_name }}"
      flavor: "{{ flavor }}"
      image: "{{ image }}"
      userdata: |
        #cloud-config
        runcmd:
        - dhclient eth0
        disable_root: True

      key_name: "{{ ansible_hostname }}"
    register: server


  - cloudflare_dns:
      account_email: "{{ cf_account }}"
      account_api_token: "{{ cf_apikey }}"

      state: present
      zone: "{{ zone }}"

      # solo affects these two attrs
      solo: yes
      record: "{{ server_name }}"
      type: "{{ item.type }}"

      value: "{{ item.value }}"
    with_items:
    - { type: A,    value: "{{ server.openstack.accessIPv4 }}" }
    - { type: AAAA, value: "{{ server.openstack.accessIPv6 }}" }

  - add_host:
      name: "{{ server.openstack.accessIPv6 }}"
      group: "{{ server_name }}"

  vars_files:
  - config.yml
  - "{{ cloud_provider }}.yml"

- hosts: all
  tasks:
  # Reduce aggressiveness of syncing
  - stat:
      path: /.ansible-sync
    register: syncmark

  - portage: sync=yes
    when: syncmark.stat.exists is defined and not syncmark.stat.exists

  - file:
      path: /.ansible-sync
      state: touch
    when: syncmark.stat.exists is defined and not syncmark.stat.exists

  # detect if systemd is installed
  - shell: qlist -I sys-apps/systemd
    failed_when: False
    register: systemd

  - portage: package={{ item }} state=absent
    when: '"" == systemd.stdout'
    with_items:
    - sys-fs/udev
    - virtual/udev

  - portage: package=dev-vcs/git state=present

  - git:
      repo: https://github.com/0xdc/overlay
      dest: /usr/local/0xdc-overlay

  - file:
      path: /etc/portage/repos.conf
      state: directory

  - copy:
      src: /usr/local/0xdc-overlay/metadata/repos.conf
      dest: /etc/portage/repos.conf/0xdc.conf
      remote_src: True

  - shell: eselect profile set 0xdc:amd64

  - portage: package=sys-apps/systemd
