- name: create openstack server
  os_server:
    cloud: "{{ cloud_provider }}"
    region_name: "{{ cloud_region }}"

    name: "{{ server_name }}{{ replica }}"
    meta: "role={{ server_name }}"
    flavor: "{{ flavor }}"
    image: "{{ image }}"
    userdata: |
      #cloud-config
      runcmd:
      - dhclient eth0

    key_name: "{{ ansible_hostname }}"
  register: server


- name: update DNS records
  cloudflare_dns:
    account_email: "{{ cf_account }}"
    account_api_token: "{{ cf_apikey }}"

    state: present
    zone: "{{ zone }}"

    # solo affects these two attrs
    solo: yes
    record: "{{ server_name }}{{ replica }}"
    type: "{{ item.type }}"

    value: "{{ item.value }}"
  loop_control:
    label: "{{ server_name }}{{ replica }}"
  with_items:
  - { type: A,    value: "{{ server.openstack.accessIPv4 }}" }
  - { type: AAAA, value: "{{ server.openstack.accessIPv6 }}" }

- name: add host to inventory
  add_host:
    name: "{{ server.openstack.accessIPv6 }}"
    group: "{{ server_name }}"
    ansible_python_interpreter: /usr/bin/python2
    fqdn: "{{ server_name }}{{ replica }}.{{ zone }}"
    server_hostname: "{{ server_name }}{{ replica }}"
