---
- block:
  - name: wait for server boot
    # I super-dislike this method...
    # ...but nothing else works :'(
    local_action: command ssh -oBatchMode=yes -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -oUser=root {{ ansible_host }} true
    register: ssh
    until: ssh|success
    retries: 15
  rescue:
  - name: delete broken server
    os_server:
      name: '{{ inventory_hostname }}'
      state: absent

      cloud: '{{ cloud_provider }}'
      region_name: '{{ cloud_region }}'
    delegate_to: localhost
  - name: cause failure
    fail: msg="Host has been removed"
