## Firstboot
- name: create repos.conf directory
  file:
    path: /etc/portage/repos.conf
    state: directory

- name: create gentoo repos.conf
  template:
    src: gentoo-repo.conf.j2
    dest: /etc/portage/repos.conf/gentoo.conf

- name: make.conf binpkg
  template:
    src: "{{ item }}"
    dest: /etc/portage/make.conf
  with_first_found:
  - "{{ inventory_hostname }}/make.conf.j2"
  - make.conf.j2

# Reduce aggressiveness of syncing
- name: check for portage tree
  stat:
    path: /usr/portage/metadata/timestamp
  register: timestamp

- block:
  - name: sync the portage tree
    portage: sync=yes

  # I don't have a good non-destructive test for this perl upgrade
  # but this shell command detects and fixes it most of the time
  - name: update perl
    shell: '(qlist -IC "virtual/perl-*"; qlist -IC "dev-perl/*") | xargs emerge -1 dev-lang/perl texinfo'
    # just run it once, if we sync the tree
  when: timestamp.stat.exists is defined and not timestamp.stat.exists
