---
zone: aestus.xyz

cloud_provider: dhc
cloud_region: RegionOne

server_name: gentoo
replicas: 1

cf_account: "{{ secret_cf_account }}"
cf_apikey:  "{{ secret_cf_apikey  }}"

sync_host: "{{ secret_sync_host }}"
